---
title: "Intro to Spatial Data "
Format: "html"
author: "Angie Kochkarova"
---

## Downloading Data and Packages

```{r}
knb_url <- "https://dev.nceas.ucsb.edu/knb/d1/mn/v2/object/urn%3Auuid%3Aaceaecb2-1ce0-4d41-a839-d3607d32bb58"

download.file(knb_url,
              destfile = "shapefile_demo_data.zip",
              mode = "wb")

dir.create("data", showWarnings = FALSE)

unzip("shapefile_demo_data.zip",
      exdir = "data",
      overwrite = TRUE)
```

```{r}
list.files("data")
```

```{r}
library(readr)
library(here)
library(sf)
library(ggplot2)
library(leaflet)
library(scales)
library(ggspatial)
library(dplyr)
```

```{r}
ak_rgns_sf <- read_sf(here("data/ak_regions_simp.shp"))
plot(ak_rgns_sf)
```

```{r}
class(ak_rgns_sf)
head(ak_rgns_sf)
st_crs(ak_rgns_sf)
```

```{r}
ak_rgns_3338_sf <- ak_rgns_sf %>%
  st_transform(crs = 3338)

plot(ak_rgns_3338_sf)
```

```{r}
ak_rgns_3338_sf %>%
  select(region)

ak_rgns_3338_sf %>%
  filter(region == "Southeast")
```

```{r}
pop_df <- read_csv(here("data/alaska_population.csv"))

pop_4326_sf <- st_as_sf(
  pop_df,
  coords = c("lng", "lat"),
  crs = 4326,
  remove = FALSE
)

head(pop_4326_sf)
```

```{r}
pop_3338_sf <- st_transform(pop_4326_sf, crs = 3338)

pop_joined_sf <- st_join(
  pop_3338_sf,
  ak_rgns_3338_sf,
  join = st_within
)

head(pop_joined_sf)
```

```{r}
pop_rgn_df <- pop_joined_sf %>%
  st_drop_geometry() %>%
  group_by(region) %>%
  summarize(total_pop = sum(population))

pop_rgn_df
```

```{r}
pop_rgn_3338_sf <- left_join(
  ak_rgns_3338_sf,
  pop_rgn_df,
  by = "region"
)

plot(pop_rgn_3338_sf["total_pop"])
```

```{r}
write_sf(pop_rgn_3338_sf, here("data/ak_regions_population.shp"))
```

```{r}
ggplot(pop_rgn_3338_sf) +
  geom_sf(aes(fill = total_pop)) +
  labs(fill = "Total Population") +
  scale_fill_continuous(
    low = "khaki",
    high = "firebrick",
    labels = comma
  ) +
  theme_bw()
```

```{r}
rivers_3338_sf <- read_sf(here("data/ak_rivers_simp.shp"))

st_crs(rivers_3338_sf)
```

```{r}
ggplot() +
  geom_sf(
    data = pop_rgn_3338_sf,
    aes(fill = total_pop)
  ) +
  geom_sf(
    data = pop_3338_sf,
    size = 0.5
  ) +
  geom_sf(
    data = rivers_3338_sf,
    aes(linewidth = StrOrder)
  ) +
  scale_linewidth(
    range = c(0.05, 0.5),
    guide = "none"
  ) +
  labs(
    title = "Total Population by Alaska Region",
    fill = "Total Population"
  ) +
  scale_fill_continuous(
    low = "khaki",
    high = "firebrick",
    labels = comma
  ) +
  theme_bw()
```

```{r}
library(prettymapr)
```

```{r}
pop_3857_sf <- st_transform(pop_3338_sf, crs = 3857)

ggplot(data = pop_3857_sf) +
  ggspatial::annotation_map_tile(
    type = "osm",
    zoom = 4,
    progress = "none"
  ) +
  geom_sf(aes(color = population), fill = NA) +
  scale_color_continuous(
    low = "darkkhaki",
    high = "firebrick",
    labels = comma
  )
```

## Leaflet section:

```{r}
epsg3338 <- leaflet::leafletCRS(
  crsClass = "L.Proj.CRS",
  code = "EPSG:3338",
  proj4def = "+proj=aea +lat_1=55 +lat_2=65 +lat_0=50 +lon_0=-154 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs",
  resolutions = 2 ^ (16:7)
)

pop_rgn_4326_sf <- pop_rgn_3338_sf %>%
  st_transform(crs = 4326)
```

```{r}
pal <- colorNumeric(
  palette = "Reds",
  domain = pop_rgn_4326_sf$total_pop
)

m <- leaflet(options = leafletOptions(crs = epsg3338)) %>%
  addPolygons(
    data = pop_rgn_4326_sf,
    fillColor = ~ pal(total_pop),
    weight = 1,
    color = "black",
    fillOpacity = 1
  ) %>%
  addCircleMarkers(
    data = pop_4326_sf,
    lat = ~ lat,
    lng = ~ lng,
    radius = ~ log(population / 500),
    fillColor = "gray",
    fillOpacity = 1,
    weight = 0.25,
    color = "black",
    label = ~ paste0(city, ", population ", comma(population))
  ) %>%
  addLegend(
    position = "bottomleft",
    pal = pal,
    values = range(pop_rgn_4326_sf$total_pop),
    title = "Total Population"
  )

m
```
